days <- c('mon','tue','wed','thr','fri','sat')
temp <- c(22.0,14.3,43.1,36.3,46,13)
rain <- c(T,T,F,T,F,F)

df <- data.frame(days,temp,rain)
print(df)
print(df[1,])
print(df[1:3,])
print(df[1:3,2:3])
print(df[,1])
print(df[,'rain'])
print(df[1:5,c('days','temp')])
print(df$days)
print(df['days'])
print(subset(df,subset=rain==T))
print(subset(df,subset=temp>25))
sorted.temp <- order(df['temp'])
print(sorted.temp)
print(df[sorted.temp,])
desc.sorted <- order(-df['temp'])
print(df[desc.sorted,])

descdollar <- order(df$temp)
print(df[descdollar,])